// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.adc.grpc;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adc_grpc_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adc_grpc_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adc_grpc_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adc_grpc_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\014com.adc.grpc\"\037\n\013UserReques" +
      "t\022\020\n\010username\030\001 \001(\t\"2\n\014UserResponse\022\020\n\010u" +
      "sername\030\001 \001(\t\022\020\n\010realname\030\002 \001(\t2[\n\013UserS" +
      "ervice\022L\n\021GetUserByUsername\022\031.com.adc.gr" +
      "pc.UserRequest\032\032.com.adc.grpc.UserRespon" +
      "se\"\000B\032\n\014com.adc.grpcB\010DataInfoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_adc_grpc_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_adc_grpc_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adc_grpc_UserRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_adc_grpc_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_adc_grpc_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adc_grpc_UserResponse_descriptor,
        new java.lang.String[] { "Username", "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
