// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.adc.grpc;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.adc.grpc.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string realname = 2;</code>
   * @return The realname.
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
